In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("bangalore_qcommerce_dataset.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 947752 entries, 0 to 947751
Data columns (total 13 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Order_ID                 947752 non-null  int64
 1   Company                  947752 non-null  object
 2   City                     947752 non-null  object
 3   Customer_Age             947752 non-null  int64
 4   Order_Value              947752 non-null  int64
 5   Delivery_Time_Min        947752 non-null  int64
 6   Distance_Km              947752 non-null  float64
 7   Items_Count              947752 non-null  int64
 8   Product_Category         947752 non-null  object
 9   Payment_Method           947752 non-null  object
 10  Customer_Rating          947752 non-null  int64
 11  Discount_Applied         947752 non-null  int64
 12  Delivery_Partner_Rating  947752 non-null  int64
dtypes: float64(1), int64(8), object(4)
memory usage: 94.0+ MB

In [4]:
df.head()

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
0,1000001,Swiggy Instamart,Banashankari,46,702,19,12.0,12,Dairy,Wallet,2,1,3
1,1000002,Flipkart Minutes,Marathahalli,56,1007,20,12.7,10,Snacks,Cash on Delivery,2,0,3
2,1000003,Flipkart Minutes,Koramangala,18,1212,17,4.8,19,Personal Care,Cash on Delivery,3,0,4
3,1000004,Swiggy Instamart,Rajajinagar,23,1179,6,6.4,2,Dairy,Credit Card,5,1,5
4,1000005,Dunzo,BTM Layout,44,586,12,2.4,13,Household,Wallet,4,0,5

In [5]:
df.describe()

,Order_ID,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
count,9.477520e+05,947752.000000,947752.000000,947752.000000,947752.000000,947752.000000,947752.000000,947752.000000,947752.000000
mean,1.500028e+06,38.471165,570.912008,16.506620,7.750048,10.313292,3.042655,0.400786,3.800295
std,2.887273e+05,12.118982,374.175332,6.340851,4.187153,5.630770,1.202499,0.490058,0.718762
min,1.000001e+06,18.000000,50.000000,5.000000,0.500000,1.000000,1.000000,0.000000,2.000000
25%,1.249939e+06,28.000000,288.000000,12.000000,4.100000,5.000000,2.000000,0.000000,3.000000
50%,1.500026e+06,38.000000,532.000000,16.000000,7.800000,10.000000,3.000000,0.000000,4.000000
75%,1.750145e+06,49.000000,797.000000,20.000000,11.400000,15.000000,4.000000,1.000000,4.000000
max,2.000000e+06,59.000000,2492.000000,40.000000,15.000000,19.000000,5.000000,1.000000,5.000000

In [6]:
df.drop_duplicates()

,Order_ID,Company,City,Customer_Age,Order_Value,Delivery_Time_Min,Distance_Km,Items_Count,Product_Category,Payment_Method,Customer_Rating,Discount_Applied,Delivery_Partner_Rating
0,1000001,Swiggy Instamart,Banashankari,46,702,19,12.0,12,Dairy,Wallet,2,1,3
1,1000002,Flipkart Minutes,Marathahalli,56,1007,20,12.7,10,Snacks,Cash on Delivery,2,0,3
2,1000003,Flipkart Minutes,Koramangala,18,1212,17,4.8,19,Personal Care,Cash on Delivery,3,0,4
3,1000004,Swiggy Instamart,Rajajinagar,23,1179,6,6.4,2,Dairy,Credit Card,5,1,5
4,1000005,Dunzo,BTM Layout,44,586,12,2.4,13,Household,Wallet,4,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
947747,1999996,Big Basket,Rajajinagar,48,72,18,3.0,19,Fruits & Vegetables,Wallet,4,0,3
947748,1999997,Swiggy Instamart,Whitefield,33,1510,18,10.5,9,Beverages,Debit Card,4,1,4
947749,1999998,Jio Mart,HSR Layout,29,637,18,2.6,6,Groceries,Cash on Delivery,3,0,5
947750,1999999,Dunzo,BTM Layout,42,1103,13,7.8,12,Snacks,Wallet,4,1,4
947751,2000000,Amazon Now,Yelahanka,19,759,18,9.4,13,Snacks,Credit Card,4,0,5

In [7]:
df.isnull().sum()

Order_ID                   0
Company                    0
City                       0
Customer_Age               0
Order_Value                0
Delivery_Time_Min          0
Distance_Km                0
Items_Count                0
Product_Category           0
Payment_Method             0
Customer_Rating            0
Discount_Applied           0
Delivery_Partner_Rating    0
dtype: int64

In [11]:
df['City'].unique()

array(['Banashankari', 'Marathahalli', 'Koramangala', 'Rajajinagar',
       'BTM Layout', 'Whitefield', 'HSR Layout', 'Electronic City',
       'Yelahanka', 'KR Puram', 'Sarjapur', 'Indiranagar', 'Jayanagar',
       'Bellandur', 'Hebbal'], dtype=object)

In [12]:
dp=pd.read_csv("qcom_time.csv")

In [13]:
dp['Order_Date']=pd.to_datetime(dp['Order_Date'])

In [16]:
df.dtypes

Order_ID                     int64
Company                     object
City                        object
Customer_Age                 int64
Order_Value                  int64
Delivery_Time_Min            int64
Distance_Km                float64
Items_Count                  int64
Product_Category            object
Payment_Method              object
Customer_Rating              int64
Discount_Applied             int64
Delivery_Partner_Rating      int64
dtype: object

In [17]:
dp.dtypes

Order_ID                int64
Customer_ID            object
Order_Date     datetime64[ns]
Order_Time     datetime64[ns]
dtype: object

In [19]:
df=df[df['Delivery_Time_Min']>0]

In [20]:
df['Company'].unique()

array(['Swiggy Instamart', 'Flipkart Minutes', 'Dunzo', 'Jio Mart',
       'Blinkit', 'Amazon Now', 'Big Basket', 'Zepto'], dtype=object)

In [21]:
dq=pd.read_csv("bangalore_dark_store_dataset.csv")

In [22]:
dq.describe()

       No_of_Dark_Stores
count          60.000000
mean            3.500000
std             2.095192
min             1.000000
25%             2.000000
50%             3.000000
75%             4.250000
max             8.000000

In [23]:
dq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Area               60 non-null     object
 1   App                60 non-null     object
 2   No_of_Dark_Stores  60 non-null     int64
dtypes: int64(1), object(2)
memory usage: 1.5+ KB

In [24]:
dq.head()

          Area               App  No_of_Dark_Stores
0  Indiranagar             Zepto                  6
1  Indiranagar           Blinkit                  4
2  Indiranagar  Swiggy Instamart                  8
3  Indiranagar             Dunzo                  7
4   Whitefield             Zepto                  7

In [25]:
dq['Area'].unique()

array(['Indiranagar', 'Whitefield', 'Koramangala', 'Electronic City',
       'Marathahalli', 'HSR Layout', 'BTM Layout', 'Yelahanka',
       'Jayanagar', 'Rajajinagar', 'Bellandur', 'Sarjapur', 'Hebbal',
       'Banashankari', 'KR Puram'], dtype=object)

In [26]:
dq.drop_duplicates()

               Area               App  No_of_Dark_Stores
0       Indiranagar             Zepto                  6
1       Indiranagar           Blinkit                  4
2       Indiranagar  Swiggy Instamart                  8
3       Indiranagar             Dunzo                  7
4        Whitefield             Zepto                  7
5        Whitefield           Blinkit                  4
6        Whitefield  Swiggy Instamart                  7
7        Whitefield             Dunzo                  5
8       Koramangala             Zepto                  6
9       Koramangala           Blinkit                  4
10      Koramangala  Swiggy Instamart                  4
11      Koramangala             Dunzo                  8
12  Electronic City             Zepto                  4
13  Electronic City           Blinkit                  3
14  Electronic City  Swiggy Instamart                  3
15  Electronic City             Dunzo                  4
16     Marathahalli             Zepto                  4
17     Marathahalli           Blinkit                  4
18     Marathahalli  Swiggy Instamart                  2
19     Marathahalli             Dunzo                  2
20       HSR Layout             Zepto                  6
21       HSR Layout           Blinkit                  6
22       HSR Layout  Swiggy Instamart                  4
23       HSR Layout             Dunzo                  6
24       BTM Layout             Zepto                  4
25       BTM Layout           Blinkit                  2
26       BTM Layout  Swiggy Instamart                  2
27       BTM Layout             Dunzo                  2
28        Yelahanka             Zepto                  2
29        Yelahanka           Blinkit                  1
30        Yelahanka  Swiggy Instamart                  2
31        Yelahanka             Dunzo                  1
32        Jayanagar             Zepto                  2
33        Jayanagar           Blinkit                  2
34        Jayanagar  Swiggy Instamart                  4
35        Jayanagar             Dunzo                  3
36      Rajajinagar             Zepto                  1
37      Rajajinagar           Blinkit                  2
38      Rajajinagar  Swiggy Instamart                  1
39      Rajajinagar             Dunzo                  1
40        Bellandur             Zepto                  7
41        Bellandur           Blinkit                  6
42        Bellandur  Swiggy Instamart                  8
43        Bellandur             Dunzo                  6
44         Sarjapur             Zepto                  4
45         Sarjapur           Blinkit                  2
46         Sarjapur  Swiggy Instamart                  4
47         Sarjapur             Dunzo                  3
48           Hebbal             Zepto                  2
49           Hebbal           Blinkit                  2
50           Hebbal  Swiggy Instamart                  1
51           Hebbal             Dunzo                  1
52     Banashankari             Zepto                  2
53     Banashankari           Blinkit                  2
54     Banashankari  Swiggy Instamart                  2
55     Banashankari             Dunzo                  1
56         KR Puram             Zepto                  2
57         KR Puram           Blinkit                  1
58         KR Puram  Swiggy Instamart                  2
59         KR Puram             Dunzo                  2

In [27]:
dq.isnull()

     Area    App  No_of_Dark_Stores
0   False  False              False
1   False  False              False
2   False  False              False
3   False  False              False
4   False  False              False
5   False  False              False
6   False  False              False
7   False  False              False
8   False  False              False
9   False  False              False
10  False  False              False
11  False  False              False
12  False  False              False
13  False  False              False
14  False  False              False
15  False  False              False
16  False  False              False
17  False  False              False
18  False  False              False
19  False  False              False
20  False  False              False
21  False  False              False
22  False  False              False
23  False  False              False
24  False  False              False
25  False  False              False
26  False  False              False
27  False  False              False
28  False  False              False
29  False  False              False
30  False  False              False
31  False  False              False
32  False  False              False
33  False  False              False
34  False  False              False
35  False  False              False
36  False  False              False
37  False  False              False
38  False  False              False
39  False  False              False
40  False  False              False
41  False  False              False
42  False  False              False
43  False  False              False
44  False  False              False
45  False  False              False
46  False  False              False
47  False  False              False
48  False  False              False
49  False  False              False
50  False  False              False
51  False  False              False
52  False  False              False
53  False  False              False
54  False  False              False
55  False  False              False
56  False  False              False
57  False  False              False
58  False  False              False
59  False  False              False

In [28]:
dq.dtypes

Area                 object
App                  object
No_of_Dark_Stores     int64
dtype: object

In [30]:
df.to_csv("cleaned_bangalore_qcommerce_dataset.csv")

In [31]:
dq.to_csv("cleaned_bangalore_dark_store.csv")

In [32]:
dp.to_csv("cleaned_qcom_time.csv")

In [ ]:
dp